### ISSUE TITLE
Error running setup libs_mlr.R in german_credit_application.R

### ISSUE THREAD

**Issue by raam93** [susanne-207/moc#1]
I was trying to run german_credit_application.R but got stuck in running libs_mlr.R without errors. This file throws me a bunch of warnings and errors on my Windows machine. I have attached the errors in a file [error_in_libs_mlr.txt](https://github.com/susanne-207/moc/files/4586502/error_in_libs_mlr.txt). Can I run german_credit_application without having to install and load all libraries in libs_mlr.R?

Further, If I ignore these errors, the code throws `object 'Predictor' not found` error at line 60 `pred = Predictor$new(model = credit.model, data = credit, class = "good", 
    conditional = TRUE)` 
 
I'm using R version 3.5.2. Perhaps this has to do with the R version or my OS. Any ideas?
Also, is there a python implementation of MOC?

**Comment by dandls** [comment]
Thank you for your comment. 
`Predictor`is an R6 object of the iml package in which `Counterfactuals` is integrated and relies on its internal structures. You can find the whole code of the iml package in the folder _iml_.

I had a look at your error file and most of the errors seem to occur due to: 
`namespace 'pillar' 1.4.2 is being loaded, but >= 1.4.3 is required` 
Please install the latest version of `pillar` and let me know if it works. 

Alternatively, you should be able to run the example if you successfully install the following packages: 
```
# To run MOC 
library(devtools)
library(ParamHelpers)
load_all("../iml/")
library("mosmafs")

# For plotting
library(ggplot2)
library(GGally)
library(metR)
library(ggExtra)
```
Let me know if either of the two options works for you.

**Comment by raam93** [comment]
Thanks for the quick response :) it worked. I had to update R and install a few dependency packages for MOC.
